CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role TINYINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS salaries (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL,
    working_date DATE NOT NULL,
    name VARCHAR(150) NOT NULL,
    price DECIMAL(15,2) NOT NULL DEFAULT 0,
    hours INT NOT NULL DEFAULT 0,
    total_salary DECIMAL(15,2) NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_salaries_user_id FOREIGN KEY (user_id) REFERENCES users(id)
);
